services:
  - type: web
    name: data-visualization-dashboard
    runtime: python
    buildCommand: |
      chmod +x install-wkhtmltopdf.sh
      ./install-wkhtmltopdf.sh
      pip install -r requirements.txt
    startCommand: "gunicorn exportVisualize:server"
    envVars:
      - key: WKHTMLTOPDF_PATH
        value: "/usr/local/bin/wkhtmltopdf"
    plan: free